// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres_driver

import (
	"context"
)

type Querier interface {
	ActivateBlockchain(ctx context.Context, arg ActivateBlockchainParams) error
	InsertBlockchain(ctx context.Context, arg InsertBlockchainParams) error
	InsertRedirect(ctx context.Context, arg InsertRedirectParams) error
	InsertSyncCheckOptions(ctx context.Context, arg InsertSyncCheckOptionsParams) error
	SelectBlockchains(ctx context.Context) ([]SelectBlockchainsRow, error)
}

var _ Querier = (*Queries)(nil)
