// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package postgresdriver

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/lib/pq"
)

const activateBlockchain = `-- name: ActivateBlockchain :exec
UPDATE blockchains
SET active = $2
WHERE blockchain_id = $1
`

type ActivateBlockchainParams struct {
	BlockchainID string       `json:"blockchainID"`
	Active       sql.NullBool `json:"active"`
}

func (q *Queries) ActivateBlockchain(ctx context.Context, arg ActivateBlockchainParams) error {
	_, err := q.db.ExecContext(ctx, activateBlockchain, arg.BlockchainID, arg.Active)
	return err
}

const insertBlockchain = `-- name: InsertBlockchain :exec
INSERT into blockchains (
        blockchain_id,
        active,
        altruist,
        blockchain,
        blockchain_aliases,
        chain_id,
        chain_id_check,
        description,
        enforce_result,
        log_limit_blocks,
        network,
        path,
        request_timeout,
        ticker
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14
    )
`

type InsertBlockchainParams struct {
	BlockchainID      string         `json:"blockchainID"`
	Active            sql.NullBool   `json:"active"`
	Altruist          sql.NullString `json:"altruist"`
	Blockchain        sql.NullString `json:"blockchain"`
	BlockchainAliases []string       `json:"blockchainAliases"`
	ChainID           sql.NullString `json:"chainID"`
	ChainIDCheck      sql.NullString `json:"chainIDCheck"`
	Description       sql.NullString `json:"description"`
	EnforceResult     sql.NullString `json:"enforceResult"`
	LogLimitBlocks    sql.NullInt32  `json:"logLimitBlocks"`
	Network           sql.NullString `json:"network"`
	Path              sql.NullString `json:"path"`
	RequestTimeout    sql.NullInt32  `json:"requestTimeout"`
	Ticker            sql.NullString `json:"ticker"`
}

func (q *Queries) InsertBlockchain(ctx context.Context, arg InsertBlockchainParams) error {
	_, err := q.db.ExecContext(ctx, insertBlockchain,
		arg.BlockchainID,
		arg.Active,
		arg.Altruist,
		arg.Blockchain,
		pq.Array(arg.BlockchainAliases),
		arg.ChainID,
		arg.ChainIDCheck,
		arg.Description,
		arg.EnforceResult,
		arg.LogLimitBlocks,
		arg.Network,
		arg.Path,
		arg.RequestTimeout,
		arg.Ticker,
	)
	return err
}

const insertRedirect = `-- name: InsertRedirect :exec
INSERT into redirects (
        blockchain_id,
        alias,
        loadbalancer,
        domain
    )
VALUES (
        $1,
        $2,
        $3,
        $4
    )
`

type InsertRedirectParams struct {
	BlockchainID string `json:"blockchainID"`
	Alias        string `json:"alias"`
	Loadbalancer string `json:"loadbalancer"`
	Domain       string `json:"domain"`
}

func (q *Queries) InsertRedirect(ctx context.Context, arg InsertRedirectParams) error {
	_, err := q.db.ExecContext(ctx, insertRedirect,
		arg.BlockchainID,
		arg.Alias,
		arg.Loadbalancer,
		arg.Domain,
	)
	return err
}

const insertSyncCheckOptions = `-- name: InsertSyncCheckOptions :exec
INSERT into sync_check_options (
        blockchain_id,
        synccheck,
        allowance,
        body,
        path,
        result_key
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
`

type InsertSyncCheckOptionsParams struct {
	BlockchainID string         `json:"blockchainID"`
	Synccheck    sql.NullString `json:"synccheck"`
	Allowance    sql.NullInt32  `json:"allowance"`
	Body         sql.NullString `json:"body"`
	Path         sql.NullString `json:"path"`
	ResultKey    sql.NullString `json:"resultKey"`
}

func (q *Queries) InsertSyncCheckOptions(ctx context.Context, arg InsertSyncCheckOptionsParams) error {
	_, err := q.db.ExecContext(ctx, insertSyncCheckOptions,
		arg.BlockchainID,
		arg.Synccheck,
		arg.Allowance,
		arg.Body,
		arg.Path,
		arg.ResultKey,
	)
	return err
}

const selectBlockchains = `-- name: SelectBlockchains :many
SELECT b.blockchain_id,
    b.altruist,
    b.blockchain,
    b.blockchain_aliases,
    b.chain_id,
    b.chain_id_check,
    b.description,
    b.enforce_result,
    b.log_limit_blocks,
    b.network,
    b.path,
    b.request_timeout,
    b.ticker,
    b.active,
    s.synccheck as s_sync_check,
    s.allowance as s_allowance,
    s.body as s_body,
    s.path as s_path,
    s.result_key as s_result_key,
    COALESCE(redirects.r, '[]') AS redirects
FROM blockchains as b
    LEFT JOIN sync_check_options AS s ON b.blockchain_id = s.blockchain_id
    LEFT JOIN LATERAL (
        SELECT json_agg(
                json_build_object(
                    'alias',
                    r.alias,
                    'loadBalancerID',
                    r.loadbalancer,
                    'domain',
                    eg.domain
                )
            ) AS r
        FROM redirects AS r
        WHERE b.blockchain_id = r.blockchain_id
    ) redirects ON true
ORDER BY b.blockchain_id
`

type SelectBlockchainsRow struct {
	BlockchainID      string          `json:"blockchainID"`
	Altruist          sql.NullString  `json:"altruist"`
	Blockchain        sql.NullString  `json:"blockchain"`
	BlockchainAliases []string        `json:"blockchainAliases"`
	ChainID           sql.NullString  `json:"chainID"`
	ChainIDCheck      sql.NullString  `json:"chainIDCheck"`
	Description       sql.NullString  `json:"description"`
	EnforceResult     sql.NullString  `json:"enforceResult"`
	LogLimitBlocks    sql.NullInt32   `json:"logLimitBlocks"`
	Network           sql.NullString  `json:"network"`
	Path              sql.NullString  `json:"path"`
	RequestTimeout    sql.NullInt32   `json:"requestTimeout"`
	Ticker            sql.NullString  `json:"ticker"`
	Active            sql.NullBool    `json:"active"`
	SSyncCheck        sql.NullString  `json:"sSyncCheck"`
	SAllowance        sql.NullInt32   `json:"sAllowance"`
	SBody             sql.NullString  `json:"sBody"`
	SPath             sql.NullString  `json:"sPath"`
	SResultKey        sql.NullString  `json:"sResultKey"`
	Redirects         json.RawMessage `json:"redirects"`
}

func (q *Queries) SelectBlockchains(ctx context.Context) ([]SelectBlockchainsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectBlockchains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectBlockchainsRow
	for rows.Next() {
		var i SelectBlockchainsRow
		if err := rows.Scan(
			&i.BlockchainID,
			&i.Altruist,
			&i.Blockchain,
			pq.Array(&i.BlockchainAliases),
			&i.ChainID,
			&i.ChainIDCheck,
			&i.Description,
			&i.EnforceResult,
			&i.LogLimitBlocks,
			&i.Network,
			&i.Path,
			&i.RequestTimeout,
			&i.Ticker,
			&i.Active,
			&i.SSyncCheck,
			&i.SAllowance,
			&i.SBody,
			&i.SPath,
			&i.SResultKey,
			&i.Redirects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
