name: Build & Test

on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - main
      - staging

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Golang ci Action
        uses: golangci/golangci-lint-action@v3

  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Validate SQLC code and mock Driver
        run: make
