name: Release & Go List

on:
  push:
    branches:
      - tag-and-release-ci
  # workflow_run:
  #   workflows: ["Lint & Test"]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branches: tag-and-release-ci

      - name: Go list
        if: steps.semrel.outputs.version != ''
        run: GOPROXY=proxy.golang.org go list -m github.com/pokt-foundation/portal-db@${{ steps.semrel.outputs.version }}
